### ISSUE TITLE
cros_ec_lpcs GOOG0004:00: EC ID not detected

### ISSUE THREAD

**Issue by penn5** [MrChromebox/firmware#116]
Hi,

Perhaps fan speeds could be exposed to lm-sensors?

Thanks!

**Comment by penn5** [comment]
Forgot to mention, of course I mean on Full ROM

**Comment by MrChromebox** [comment]
fan controls are exposed to the OS via the EC, which is supported by the crosec-lpc driver.  They can also be adjusted via Google's ectool, which can be built as part of the EC firmware source code

**Comment by penn5** [comment]
The linux cros-ec-lpcs driver included in ubuntu fails for me. In dmesg I see the error `cros_ec_lpcs GOOG0004:00: EC ID not detected`. That error is coming from https://github.com/torvalds/linux/blob/master/drivers/platform/chrome/cros_ec_lpc.c#L261
There are no errors in the modprobe.

```
$ cat /sys/devices/pci0000:00/0000:1f.0/PNP0C09:00/GOOG0004:00/firmware_node/path
\_SB-.PCI0.LPCB.EC0_.CREC
```
seems to suggest that it _is_ the EC, so perhaps the firmware utility script has flashed a custom EC firmware? Is there a way for me to manually wipe the RW EC firmware to force a factory restore of the EC?

NOTE: I've renamed the issue to reflect this module failure

**Comment by penn5** [comment]
@MrChromebox just a ping, I guess you didn't read this issue because its closed. Please reopen.

**Comment by MrChromebox** [comment]
I'm not entirely sure this is a firmware issue but I'll investigate

edit: this driver fails to load with stock+RW_LEGACY firmware as well, with the same error; only case I can find this driver to load properly is under ChromeOS/ChromiumOS.  the driver loads properly under ChromiumOS with both stock+RWL and UEFI firmware, so that pretty much tells me the issue is with the upstream driver, not the firmware

**Comment by penn5** [comment]
Ok, thanks
