### ISSUE TITLE
Build coreboot (UEFI) for stumpy from source

### ISSUE THREAD

**Issue by iokill** [MrChromebox/firmware#185]
Hi!

I've tried to build the latest coreboot (full rom) 4.11 for my samsung chromebox (stumpy).
As noted in #98 and #25 I need to gather the required blobs myself. As I'm new to all of this I've got a few questions:

The microcode blob used by your latest coreboot rom (https://www.mrchromebox.tech/files/firmware/full_rom/coreboot_tiano-stumpy-mrchromebox_20191201.rom) seems to be different than the latest intel blob I've found in `3rdparty/intel-microcode/intel-ucode/06-2a-07`.  

```
$ cbfstool ~/Downloads/coreboot_tiano-stumpy-mrchromebox_20191201.rom print
FMAP REGION: COREBOOT
Name                           Offset     Type           Size   Comp
...
cpu_microcode_blob.bin         0x8c40     microcode       26624 none
...
```

vs. my build using `3rdparty/intel-microcode/intel-ucode/06-2a-07`

```
$ cbfstool build/coreboot.rom print
FMAP REGION: COREBOOT
Name                           Offset     Type           Size   Comp
...
cpu_microcode_blob.bin         0x8c40     microcode       12288 none
...
```
What microcode version/release are you using and is the one I found the correct one?

As for the other blobs, I've found most of what I'm missing in `3rdparty/blobs/mainboard/samsung/stumpy/` - are these usable/correct for `CONFIG_IFD_BIN_PATH` and `CONFIG_ME_BIN_PATH`?

Thanks,
-- David

**Comment by MrChromebox** [comment]
you actually don't need any blobs to build STUMPY, you can use the coreboot supplied ones for MRC and microcode. The IFD and ME are only needed if building a "full" image, but that's only needed for external flashing. When flashing internally, you can only write the BIOS region of the chip (the IFD and ME are not writeable) so no need to worry about them

I include the microcode for both SNB and IVB CPUs, since one can run an IVB CPU in STUMPY without issue. Currently including microcode for CPUID 206A7 version 2F and 306A9 version 21

**Comment by MrChromebox** [comment]
closing since all boards can now be built from source by cloning my repo/submodules
