### ISSUE TITLE
any chance for support?

### ISSUE THREAD

**Issue by wishUponAstarTonight** [MrChromebox/firmware#224]
hello.
I bought a new bottom-of-the-line chrome OS laptop from walmart ($160) it’s a Lenovo ideapad 3. My whole plan was to use this hardware to boot chrome and a Linux bootable USB (tails) I already have.
But it feels like that’s impossible… I tried the old John Lewis tool, it says “lick is currently not supported at all”. The mrchromebox tool all the options are greyed out and it says my device isn’t supported.
I have developer mode on, write protect off… when I bootup and press CtrlU it just beeps at me and does nothing.
Any chance you’ll support this device in the future?
I am a noob, is there any other firmware or methods of booting from a usb?

**Comment by MrChromebox** [comment]
> I tried the old John Lewis tool

John Lewis left the Chromebook scene years ago, his work is abandoned/unsupported. why would you even think of trying it on a brand new device?

> The mrchromebox tool all the options are greyed out and it says my device isn’t supported.

because it's not supported.

> I have developer mode on, write protect off… when I bootup and press CtrlU it just beeps at me and does nothing.

why would you disable WP? has nothing to do with booting Linux. CTRL+U boots ChromeOS from USB.

> Any chance you’ll support this device in the future?

probably not, legacy boot mode is broken on Google's end
