### ISSUE TITLE
Link (Chromebook Pixel 2013) slow Graphics

### ISSUE THREAD

**Issue by renr4** [MrChromebox/firmware#289]
Along with the [No turbo](https://github.com/MrChromebox/firmware/issues/195) issue on Link, I also noticed that the HW acceleration works slow. For example `vblank_mode=0 glxgears` gives me around 6000 fps on the stock firmware, but on UEFI it's 3000 and lower. So, it's 2 times slower. And the whole UI (scrolling pages, moving windows) slightly lagging. I tried different distros and kernes (even ubuntu 14.04), and no changes. This issue is not on the OS side.

**Comment by MrChromebox** [comment]
tried Cloudready or Brunch for most accurate comparison? could be a Chromium kernel tuning issue. Or directly related to lack of turbo boost since that effects the GPU too IIRC

**Comment by renr4** [comment]
No, but frame drops were noticeable without tests. I tried both legacy and UEFI on the same distro, with the same kernel params. UEFI were about 2x slower.

**Comment by renr4** [comment]
The recent update didn't fix it. Same slow graphics and no turbo.

**Comment by MrChromebox** [comment]
not surprising as no specific changes were made to address the issue

**Comment by bpvarsity** [comment]
Can confirm the issue with my Chromebook Pixel 2013 as well

**Comment by elektroencefalografista** [comment]
Same on mine, running the latest firmware

**Comment by elektroencefalografista** [comment]
It seems like the issue is related to CPU power being misreported.
![power throttling](https://user-images.githubusercontent.com/30481447/183266427-773f4fce-c296-4c22-8efe-aef793e4cb38.png)
In hwinfo on Windows the CPU power is being reported around 35-36W with very little change compared to CPU load, while PL1 limit is set at 17W. 
This would definitely explain no turbo and poor GPU performance (due to clocks being stuck at the lowest state). 
@MrChromebox is there a chance you could take another look at this?

edit: sure enough, after using ThrottleStop to get around power limits the CPU is able to go past 1.8GHz. GPU is able to hit higher clocks as well.

**Comment by MrChromebox** [comment]
interesting, I'll see what I can find

**Comment by MrChromebox** [comment]
looks like the non-turbo ratio is locked at 18 (1.8GHz) preventing SpeedStep (or any sort of power management) from functioning. Not seeing the issue on a SandyBridge Chromebox so need to figure out what's different

**Comment by elektroencefalografista** [comment]
That sounds correct to me, iirc this CPU has a non-turbo ratio of 18 and turbo of 28 for single thread workloads.
I don't think the issue is related to Speedstep. I've used [this tool](https://github.com/horshack-dpreview/setPL) to compare the chromebook to my Thinkpad X220 (SB-based) and both behave the same way - if CPU package power is higher than PL1, the ratio won't go over non-turbo clocks. Both laptops turbo properly if PL1/PL2 are set sufficiently high.
I still think the CPU power is being misreported for some reason. I saw ~47-49W being reported at 2.6GHz with all threads loaded. Sounds unreasonable for an U-series Ivy Bridge CPU.

**Comment by MrChromebox** [comment]
I agree, ~33W pkg power makes no sense. But also seems like the non-turbo multiplier is fixed at 18, which it shouldn't be. I'm unable to find another U-series SNB/IVB model with coreboot to compare; the x220/230 use M-series CPUs (I tested an x230 here and it does not display the same behavior w/r/t the multiplier or pkg power, so same as your x220)

**Comment by coolstar** [comment]
Turbo boost is working fine here on Link w/ coreboot 4.20 and Win10 22H2

**Comment by renr4** [comment]
Just installed UEFI on my link and both [turbo boost](https://github.com/MrChromebox/firmware/issues/195) and GPU seem to be working fine now.

**Comment by MrChromebox** [comment]
great, thanks for the update
