### ISSUE TITLE
4.14 on Sandybridge, Intel HD not detected in Windows

### ISSUE THREAD

**Issue by jd7654** [MrChromebox/firmware#299]
Did upgrade to 4.14 on Acer C710, which is multiboot Windows, Cloudready and Linux.

Initially looked OK, but then a new Cloudready 92.3.4 upgrade changed partition layout from 27 to 12 partitions and broke Windows. After reinstalling Windows, graphics was only available at Windows Basic adapter. Downgrade to 4.12 allowed Windows to detect and load Intel HD drivers, which also restored sleep function.

Other issue related to Cloudready is that firmware script still tries to use sda27 as ESP on Cloudready instead of sda12 like on a Chromebook.
https://neverware.zendesk.com/hc/en-us/community/posts/1500000973861-Notice-Partition-migration-in-v90-and-v91
Although this point may be moot since the newer kernels in Cloudready/ChromeOS is not permissive enough to allow firmware script to run anyway, has to be run from another Linux.

Have another C710 with ChromeOS (brunch) and Linux dual boot and seems to be OK with 4.14 so far.
Previously had to downgrade from 4.13 back to 4.12 because of issue booting Linux kernels directly on 4.13.
But 4.12 has that nasty bug where the nvram is periodically corrupted causing the keyboard to stop working on boot. But luckily this can be recovered with a USB boot and clearing nvram.

**Comment by MrChromebox** [comment]
I'm not able to reproduce this here, at least not on the devices I have. Did a clean install of Win11 on STUMPY and no issues with the HD3000 display driver being automatically downloaded/installed via WU.

Also, I've fixed the CloudReady partition identification issue, but as you noted it's moot due to the kernel being locked down and flashrom not being able to read/write the firmware
