### ISSUE TITLE
UEFI support for Chromebase 22" All In One

### ISSUE THREAD

**Issue by SuperKnux** [MrChromebox/firmware#366]
Model Board: DOOLY
Base Board: Puff
Processor: Intel Pentium 6405U (Comet Lake)

I dunno what else to put in here, so if there's anything I'm missing, tell me.

**Comment by MrChromebox** [comment]
just added RW_LEGACY support, LMK if that works. Don't want to add an untested UEFI Full ROM firmware for it unless you have a Suzy-Q cable to unbrick

**Comment by ghost** [comment]
I own this chromebase, found the jumper on the motherboard.

RW_LEGACY works, I installed Arch instead of Chrome OS.

I don't know if I missed something, but the live (installation media) boots in UEFI mode. I installed Arch Linux by formatting the SSD to GPT (with a bios boot partition). I use GRUB. I tried both GRUB installation methods, BIOS/GPT and UEFI.
The first did nothing, the second worked. But the bootloader does not launch GRUB automatically. If I let it, it shows an error that there is no UEFI OS on the SSD. I have to select "Boot from file", navigate to /boot/EFI/grub64.efi to launch Arch.

The firmware allows to directly manage UEFI boot entries from within its boot-time interface. There is an "Add New Boot Option" choice which enables to manually enter the EFI application location, but the entry is not kept between reboots.

EDIT: same problem with efibootmgr or bcfg.

This means I have to keep a USB keyboard plugged in every time I want to boot the computer.

I'd love to test a UEFI Full ROM but I don't own a Suzy-Q cable.

**Comment by ghost** [comment]
Found a solution here : #409

**Comment by letrain02** [comment]
> I own this chromebase, found the jumper on the motherboard.


i noticed ghost's account has been deleted
where is the jumper? i've googled and googled... and i'm probably just not typing in the right words.

**Comment by MrChromebox** [comment]
all of the 10th-gen/puff-based Chromeboxes use a similar board layout. My supported devices page shows the board / jumper location for several of them -- use those as a reference
