### ISSUE TITLE
When the chromebook is in standby and you connect a usb device, the usb device light up whereas it should not.

### ISSUE THREAD

**Issue by jeremy447** [MrChromebox/firmware#48]
Hello,

As I say in the title, when the chromebook is in standby and you connect a usb device, the usb device light up whereas it should not.

Obviously not a very important bug but I just wanted to let you know :)

Thanks !

**Comment by jeremy447** [comment]
Oh I forgot to say that I have a Falco with the latest uefi full rom on Fedora 25 ;)

**Comment by ReddestDream** [comment]
If you let it sit in standby for a bit, that should stop. Sometimes it takes a bit for the USB ports to power down.

**Comment by jeremy447** [comment]
Ok I will try :)

**Comment by ReddestDream** [comment]
@Paviluf Are you also ready to close this one?

**Comment by jeremy447** [comment]
No I need to do more tests but it seem that the usb port doesn't completely switch off when the chromebook is in standby. For example, when I switch the chromebook to standby with a usb mouse attached, the usb mouse switch off and that's perfect. But if I connect an other usb device (or if I unplug / plug the usb mouse) to the chromebook, this usb device will switch on.

**Comment by ReddestDream** [comment]
So, when you say "standby," you are talking about a sleep state, one you can wake out of with the keyboard, as opposed to a hibernate state, one you use the power button and go back though the firmware startup to get out of, right?

That USB behavior is normal in sleep. Otherwise, you couldn't wake from sleep with a USB mouse, etc. I still don't get the issue here. USB power shouldn't be turned off in the sleep state.

My guess is that on sleep, connected devices are sent a signal that they can go to a lower power mode, but devices that are not connected at that time do not get that so they connect at full power. That behavior seems to match other PCs . . . Some of them wake when you connect USB devices in sleep.

**Comment by jeremy447** [comment]
I mean when you close the lid

**Comment by ReddestDream** [comment]
Just closing the lid is normal sleep (S3), so my comment above applies.

Eventually, after enough time, the system can perform (depending on OS settings) a full transition to hibernate (S4) but that usually takes at least an hour. At that point, the power to the USB ports will be off.

**Comment by jeremy447** [comment]
You seem to be right ! I thought the usb ports should be off in standby, since my usb mouse was off.
Thanks !
