### ISSUE TITLE
peppy: keyboard input not detected in systemd-boot 

### ISSUE THREAD

**Issue by Zirkelite** [MrChromebox/firmware#51]
When using systemd-boot as UEFI bootloader, systemd-boot does not detect keyboard input when using the integrated keyboard. However, an external USB keyboard works as expected. Other bootloaders such as GRUB work correctly with the integrated keyboard.

This is potentially a firmware issue, since keyboard input in systemd-boot works normally on other computers with different keyboard combinations as expected.

**Comment by ReddestDream** [comment]
Yeah. I've also noticed that. I'm expecting it will be fixed once the EC firmware keyboard fix is in to make the keyboard properly PS/2 compliant. I should check if it fixes systemd-boot, but it does fix Windows installer and BSDs w/o a Chromebook/Coreboot keyboard workaround.

https://github.com/MattDevo/firmware/issues/42

I'll confirm it fixes systemd-boot later today.

It's odd tho because bootloaders should inherit the working driver from the Tiano payload. This is how GRUB and rEFInd are able to work . . .

Make sure you have the latest UEFI firmware (01/27 for Peppy).

**Comment by ReddestDream** [comment]
Okay. This is odd. I tested out systemd-boot and even with the keyboard EC firmware fixes, it still doesn't work in systemd-boot. Something we will have to look into. Thanks for letting us know.

**Comment by ReddestDream** [comment]
Figured out why this is happening. Should be fixed in the next major update.

https://github.com/ReddestDream/chrome-ec/commit/4759fa2e640368c87145df4da9575d04fa247b78

**Comment by MrChromebox** [comment]
fixed via EC firmware update in 2017.02.21 release
