### ISSUE TITLE
Possible boot issues

### ISSUE THREAD

**Issue by jeremy447** [MrChromebox/firmware#55]
Hello,

I see these 3 messages everytime my Falco boot with Fedora 25. I don't know if it's Fedora problems or firmware problems.

> System BootOrder not found. Initializing defaults.
> Creating boot entry "Boot0002" with label "Fedora" for file "\EFI\fedora\shim.efi"

![screenshot from 2017-03-28 22-30-09](https://cloud.githubusercontent.com/assets/17159065/24479146/1bd2af54-14de-11e7-9a50-1693b3c6e8ae.png)

> EFI stub: ERROR: Could not determine UEFI Secure Boot status.

![screenshot from 2017-03-28 22-31-16](https://cloud.githubusercontent.com/assets/17159065/24479183/4686ab42-14de-11e7-9ebf-964336ede167.png)

> usb 1-4: string descriptor 0 read error: -22

![screenshot from 2017-03-28 22-32-27](https://cloud.githubusercontent.com/assets/17159065/24479221/6837930a-14de-11e7-9c32-ae8200c10e97.png)

Thanks !

**Comment by ReddestDream** [comment]
The first error is because the firmware doesn't support boot orders (yet).

https://github.com/MattDevo/firmware/issues/4

The second error is because the firmware doesn't have Secure Boot (yet).

So, obviously, since it doesn't exist, it can't find the status.

The third error is caused by a bad USB device name in the Bluetooth part of the Wifi device.

This is reported by the hardware itself and can't be fixed in firmware.

Hope this helps! ^_^

**Comment by jeremy447** [comment]
> Hope this helps! ^_^

Yes ! Thank you !
