### ISSUE TITLE
EMMC not appear when try install windows 11 on Acer Chromebook Spin 514 AMD Ryzen 3 3250c

### ISSUE THREAD

**Issue by metalex10** [MrChromebox/firmware#556]
EMMC not appear when try install windows 11 on Acer Chromebook Spin 514 AMD Ryzen 3 3250c?

Is problem of UEFI or other thing

I also tried to create with windows to go with a micro SD which always works but it doesn't boot from SD either.

Any recommendation?

**Comment by MrChromebox** [comment]
known issue, duplicate issue, warned before you even flashed.

**Comment by socram8888** [comment]
I'm considering getting an AMD Picasso Chromebook (a Lenovo 300e specifically), since they are really cheap, and found about the eMMC booting issue. I've seen looking through recent Coreboot commits https://github.com/MrChromebox/coreboot/commit/850b6c6254ab34cdbda24818cb0ecca484c01c86, which adds the generic AMD eMMC driver for the Google Trembyle and Dalvoz device trees that all devices extend from.

If I were to compile from source code (given I've looked at https://github.com/MrChromebox/scripts/blob/master/sources.sh and, while it says the date, it doesn't list what the Git head was when they were built so I am unsure if those include it or not), would be booting from eMMC expected to work?

**Comment by MrChromebox** [comment]
> would be booting from eMMC expected to work?

no, because it's not a coreboot issue, it's an edk2 one. There is no support for MMIO eMMC/SD devices (which is what Picasso Chromebooks use) in edk2 when used as a coreboot payload currently.

**Comment by socram8888** [comment]
Alright, perfect, thanks for your response!

**Comment by metalex10** [comment]
> > would be booting from eMMC expected to work?
> 
> no, because it's not a coreboot issue, it's an edk2 one. There is no support for MMIO eMMC/SD devices (which is what Picasso Chromebooks use) in edk2 when used as a coreboot payload currently.

> Alright, perfect, thanks for your response!


I solved my own problem by buying an ngff to m2 converter on Aliexpress, I installed a 256gb m2 and from there the entire installation, I hope this information is useful to you, greetings
