### ISSUE TITLE
ASUS Chromebook Flip C302C.Can't install windows and boot from emmc

### ISSUE THREAD

**Issue by liuxiawei** [MrChromebox/firmware#87]
Thank author for this script.There is no wrong when I use Fedora Live.But I always stop with the microsoft logo during install the windows or run win8PE. And when use some DOS tool I will get black screen and can do nothing. and When we enter the list of boot drive,I can't boot from the first option(the hardwave,emmc).
I don't know the problem is about the machine or this script,but please help.
Sorry for my poor English.

**Comment by MrChromebox** [comment]
the stock ChromeOS firmware is not capable of booting Windows via Legacy Boot mode (ie, SeaBIOS) -- for that you will need custom UEFI firmware, like every other ChromeOS device.  UEFI firmware for Skylake devices (like CAVE) are next on the list, but Windows is not likely to be 100% functional due to lack of missing drivers for audio, touchscreen, sensors, etc
