### ISSUE TITLE
EDGAR: No Block Devices for MMC detected after latest Full ROM.

### ISSUE THREAD

**Issue by chaoticryptidz** [MrChromebox/firmware#91]
Boots into grub, can view MMC in there, however can't find them when the linux kernel is loaded.
Tested on GalliumOS (2.1 and 2.2 prerelease) and Kali's (4.14...)kernel.
The only way (as of quick testing) I know I can access the MMC is on the 9,30 amd64 debian netinst iso but I can't mount my ext partition because of how minimal it is so I can't reflash my UEFI with the bios.bin that was left in /tmp (which I know is still there because I can see it in grub/EFI Shell)...
Somehow you have broken MMC support in these Linux Distros.

**Comment by MrChromebox** [comment]
if your device is booting into grub, then it's not having an issue seeing the eMMC, since grub is *on* the eMMC.  I really don't know what you're talking about but I'm about 98% sure it's not a firmware issue /not an eMMC detection issue since it works fine here on my Edgar as well as several others I've personally confirmed.  

I think you're getting the grub and EFI shells confused, and that you simply need to ensure your bootloader is installed to the correct location, as per the notes on the FAQ page
